version: "3.7"
networks: 
  development: 
    name: development

services:
  portainer: 
    container_name: portainer
    image: portainer/portainer-ce:latest
    networks: 
      - development
    ports:
      - "9443:9443"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.local/share/docker/persistence:/data"
